fix(app): routes don't always stack anymore
HPI-de/hpi-flutter pull request #106
Opened 2019-10-15 19:16 UTC by marcelgarus

**Fixes: #105**

**Checklist**

- [x] Commit messages follow conventionalcommits.org
- [x] Tested on actual devices
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Changes**

The routes don't always stack anymore.

2019-10-15 19:22 UTC, phpfs approved these changes
seems fine

2019-10-15 20:37 UTC, JonasWanke requested changes
I'd still leave the dashboard as a top-level route, i.e. always navigate back to the dashboard before closing the app when using the back button.

2019-10-15 20:39 UTC, phpfs commented
@JonasWanke this could make sense on Android - but might confuse iOS users.

2019-11-14 19:26 UTC, JonasWanke approved these changes

2019-11-14 19:27 UTC, merged