fix(course): fix scrolling behaviour of course and courseseries list
HPI-de/hpi-flutter pull request #86
Opened 2019-10-08 20:39 UTC by ctiedt

Fixes issues that became apparent during testing, but were not recorded as issues where these lists would not display properly.

**Checklist**

- [x] Commit messages follow conventionalcommits.org
- [x] Tested on actual devices
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2019-10-08 20:45 UTC, MarcelGarus requested changes

2019-10-08 20:45 UTC, marcelgarus commented on lib/course/widgets/course_page.dart
> +                    : HpiL11n.get(context, 'loading')),
I think `snapshot.error?.toString() ?? HpiL11n.get(...)` would be cleaner.

2019-10-08 20:45 UTC, marcelgarus commented on lib/course/widgets/course_page.dart
> -                  : HpiL11n.get(context, 'loading')),
Same as above, I think `snapshot.error?.toString() ?? HpiL11n.get(...)` would be cleaner.

2019-10-09 11:32 UTC, JonasWanke approved these changes

2019-10-09 11:33 UTC, merged