fix: Clicking on HPI logo could open browser with hpi.de
HPI-de/hpi-flutter pull request #92
Opened 2019-10-14 15:02 UTC by ctiedt

**Fixes: #88 **

**Checklist**

- [x] Commit messages follow conventionalcommits.org
- [x] Tested on actual devices
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Changes**
The HPI logos on the dashboard and in the bottom drawer are now buttons that lead to hpi.de.
This branch also includes minor changes to the layout of the bottom drawer to make the HPI logo and settings button more centered.

2019-10-15 17:24 UTC, MarcelGarus requested changes

2019-10-15 17:24 UTC, marcelgarus commented on lib/app/widgets/dashboard_page.dart
> +                  constraints: BoxConstraints(maxWidth: 200, maxHeight: 100),
Better use a `LimitedBox` with a `maxWidth` and -`height` here

2019-10-15 17:24 UTC, marcelgarus commented on lib/app/widgets/dashboard_page.dart
> +                alignment: Alignment.topRight,
Better merge those into a `Container` with `padding` and `alignment`

2019-10-15 17:24 UTC, marcelgarus commented on lib/app/widgets/dashboard_page.dart
> +            },
🏹 f.

2019-10-15 17:24 UTC, marcelgarus commented on lib/app/widgets/main_scaffold.dart
> +import 'package:flutter/material.dart' as prefix0;
Ugh this looks like an artifact of https://github.com/dart-lang/sdk/issues/36890

2019-10-15 17:24 UTC, marcelgarus commented on lib/app/widgets/main_scaffold.dart
> +                  },
🏹

2019-10-15 18:10 UTC, MarcelGarus approved these changes

2019-10-15 18:23 UTC, MarcelGarus requested changes
* We shouldn't display Material ink wells when clicking on the logo. So, instead of using an `InkWell`, a `GestureDetector` might be sufficient.
* On the dashboard, we shouldn't detect taps on the whole header, just on the logo.
* On the dashboard, the logo should align with the carousel thingies below.

2019-10-16 06:16 UTC, phpfs commented
This feature might be confusing if one accidentally activates the button. Maybe an alert with confirmation helps :)

2020-01-23 16:44 UTC, marcelgarus commented
@ctiedt An `AlertDialog` for confirmation would indeed be a great solution.

2020-05-14 16:09 UTC, closed without merging