feat(course, news): add share and open in browser buttons
HPI-de/hpi-flutter pull request #98
Opened 2019-10-14 18:19 UTC by ctiedt

**Fixes: #89**
**Fixes: #90**

**Checklist**

- [x] Commit messages follow conventionalcommits.org
- [x] Tested on actual devices
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2019-10-15 17:31 UTC, MarcelGarus approved these changes
Approving, but still `await`ing approval of @JonasWanke

2019-10-15 17:31 UTC, marcelgarus commented on lib/course/widgets/course_detail_page.dart
> +                }
Is probably okay, although a `switch` is probably more suited for this use case

2019-10-15 20:43 UTC, JonasWanke requested changes
We should move all actions to the `BottomAppBar`. _Share_ can have its own icon whereas _open in browser_ and _send feedback_ stay in the overflow menu

2020-01-23 16:37 UTC, MarcelGarus approved these changes

2020-01-23 16:37 UTC, marcelgarus commented
@JonasWanke ping :squirrel:

2020-01-24 20:21 UTC, JonasWanke approved these changes

2020-01-30 20:27 UTC, merged